In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]


In [12]:
print('1D Array')
a = np.array([1, 2, 3, 4, 5])
print(a)


#---------------------------------------


print('2D Array')
b = np.array([[1, 2, 3, 4, 5],[5, 6, 7, 8, 9]])
print(b)


#-------------------------------------------------
print('3D Array')
c = np.array([[1, 2, 3, 4, 5],[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]])
print(c)


1D Array
[1 2 3 4 5]
2D Array
[[1 2 3 4 5]
 [5 6 7 8 9]]
3D Array
[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 2 3 4 5]]


In [8]:
type(a)

numpy.ndarray

size = Tells about no. of elements in that array

In [9]:
print(a.size)
print(b.size)

5
15


shape = (rows, cols)

In [17]:
print(a.shape)
print(c.shape)

(5,)
(3, 5)


dtype = type of data present in the array

In [14]:
print(b.dtype)
print(c.dtype)

int64
int64


arr.transpose()

In [15]:
c.transpose()

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 3],
       [4, 8, 4],
       [5, 9, 5]])

*** Part 2 ***

np.empty((rows, cols), dtype)

In [19]:
np.empty((4, 4), dtype=float)

array([[4.67296746e-307, 1.69121096e-306, 2.22522461e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 2.04712907e-306, 3.49698923e-317,
        1.11253905e-308]])

np.ones((rows, cols), dtype)

In [21]:
x = np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [22]:
x = np.ones((3, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
x = np.ones((3, 5), dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
x = np.zeros((3, 5), dtype=bool)
print(x)

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [28]:
x = np.ones((3, 5), dtype=bool)
print(x)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


*** Part 3 ***

np.arange(start, end, step)

In [29]:
a = np.arange(1, 28)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [30]:
a = np.arange(1, 28, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27]


arr.reshape((rows, cols))

In [34]:
a = a.reshape((7, 2))
print(a)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]]


In [38]:
b = np.arange(1, 100, 2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [40]:
b = b.reshape((10, 5))
print(b)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


flatten() flattened to 1d array...just the reverse process of reshape

In [41]:
b = b.flatten()
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


a.ravel(): i) Return only reference/view of original array ii) if you modify the array you would notice that the value of original array also changes. iii) Ravel is faster than flatten() as it does not occupy any memory iv) Ravel is a library-level function

a:flatten(): i) Return copy of original array ii) if you modify any value of this array value of original array is not affected. iii) flatten() is comparatvely slower than ravel() as it occupies memory. iv) Flatten is a method of an ndarray object