In [3]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]


In [12]:
print('1D Array')
a = np.array([1, 2, 3, 4, 5])
print(a)


#---------------------------------------


print('2D Array')
b = np.array([[1, 2, 3, 4, 5],[5, 6, 7, 8, 9]])
print(b)


#-------------------------------------------------
print('3D Array')
c = np.array([[1, 2, 3, 4, 5],[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]])
print(c)


1D Array
[1 2 3 4 5]
2D Array
[[1 2 3 4 5]
 [5 6 7 8 9]]
3D Array
[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 2 3 4 5]]


In [8]:
type(a)

numpy.ndarray

size = Tells about no. of elements in that array

In [9]:
print(a.size)
print(b.size)

5
15


shape = (rows, cols)

In [17]:
print(a.shape)
print(c.shape)

(5,)
(3, 5)


dtype = type of data present in the array

In [14]:
print(b.dtype)
print(c.dtype)

int64
int64


arr.transpose()

In [15]:
c.transpose()

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 3],
       [4, 8, 4],
       [5, 9, 5]])

*** Part 2 ***

np.empty((rows, cols), dtype)

In [19]:
np.empty((4, 4), dtype=float)

array([[4.67296746e-307, 1.69121096e-306, 2.22522461e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 2.04712907e-306, 3.49698923e-317,
        1.11253905e-308]])

np.ones((rows, cols), dtype)

In [21]:
x = np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [22]:
x = np.ones((3, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
x = np.ones((3, 5), dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
x = np.zeros((3, 5), dtype=bool)
print(x)

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [28]:
x = np.ones((3, 5), dtype=bool)
print(x)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


*** Part 3 ***

np.arange(start, end, step)

In [29]:
a = np.arange(1, 28)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [30]:
a = np.arange(1, 28, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27]


arr.reshape((rows, cols))

In [34]:
a = a.reshape((7, 2))
print(a)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]]


In [14]:
b = np.arange(1, 100, 2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [15]:
b = b.reshape((10, 5))
print(b)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


flatten() flattened to 1d array...just the reverse process of reshape

In [16]:
b = b.flatten()
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


a.ravel(): i) Return only reference/view of original array ii) if you modify the array you would notice that the value of original array also changes. iii) Ravel is faster than flatten() as it does not occupy any memory iv) Ravel is a library-level function

a:flatten(): i) Return copy of original array ii) if you modify any value of this array value of original array is not affected. iii) flatten() is comparatvely slower than ravel() as it occupies memory. iv) Flatten is a method of an ndarray object

In [17]:
b = b.ravel()
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


*** Part 4 ***

In [23]:
a = np.arange(1, 21)
a = a.reshape(5, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [24]:
a[0]

array([1, 2, 3, 4])

In [36]:
a[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
a[0:5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
a[:,2]

array([ 3,  7, 11, 15, 19])

In [38]:
a[2:5, 3]

array([12, 16, 20])

In [44]:
a[:, 1:5]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [46]:
a[:, 1:5].dtype

dtype('int32')

*** Part 5 ***

In [58]:
a = np.arange(0, 18).reshape((6, 3))
b = np.arange(20, 38).reshape((6, 3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [49]:
a + b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [50]:
np.add(a, b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [51]:
a - b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [52]:
np.subtract(a, b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [53]:
np.multiply(a, b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [54]:
np.divide(a, b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [62]:
a @ b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [61]:
b = b.reshape((3, 6))
print(b)

[[20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]]


In [63]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [64]:
b.max()

37

In [65]:
b.min()

20

In [66]:
b.argmax()

17

In [67]:
np.sum(b)

513

axis = 1 means rows....means 1st row sum is 135, 2nd row sum is 171 and 3rd row sum is 207

In [70]:
np.sum(b, axis = 1)

array([135, 171, 207])

axis = 0 means cols....means 1st col sum is 78, 2nd col sum is 81 and 3rd col sum is 84 and so on

In [71]:
np.sum(b, axis = 0)

array([78, 81, 84, 87, 90, 93])

In [72]:
np.mean(b)

28.5

In [73]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [74]:
np.std(b)

5.188127472091127

In [75]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

*** Part 6 *** Pre requisite is Matplotlib and seaborn

In [2]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [4]:
np.pi

3.141592653589793

In [5]:
np.sin(np.pi/2)

1.0

In [6]:
np.sin(np.pi/6)

0.49999999999999994

In [7]:
np.cos(np.pi/2)

6.123233995736766e-17

In [8]:
np.tan(np.pi/2)

1.633123935319537e+16

*** Part 7 ***

In [62]:
np.random.random(1)

array([0.20823528])

In [76]:
np.random.random(2)

array([0.40963052, 0.6793536 ])

In [18]:
np.random.random((2, 2))

array([[0.66506656, 0.41306626],
       [0.95490105, 0.50411737]])

In [104]:
np.random.randint(1, 10)

4

In [21]:
np.random.randint(1, 10, (2,2))

array([[6, 5],
       [5, 7]])

np.random.randint(start_val, end_val, (1d/2d/3d/..nd array, no. of rows, no. of columns))

In [28]:
np.random.randint(1, 10, (3,4,5))

array([[[1, 6, 1, 8, 8],
        [3, 2, 5, 9, 4],
        [6, 5, 9, 1, 2],
        [3, 5, 8, 5, 6]],

       [[4, 9, 7, 3, 3],
        [1, 9, 2, 2, 6],
        [4, 2, 5, 8, 1],
        [1, 4, 7, 8, 5]],

       [[2, 1, 1, 1, 9],
        [9, 7, 7, 4, 2],
        [5, 9, 9, 1, 3],
        [9, 5, 5, 3, 2]]])

In [111]:
np.random.rand(2, 2)

array([[0.33707223, 0.04107174],
       [0.55938617, 0.64091526]])

In [32]:
np.random.randn(2, 2)

array([[ 0.24302256,  0.41360846],
       [-0.1058111 , -0.78948758]])

In [33]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [34]:
np.random.choice(a)

4

*** Part 8 ***

In [112]:
s1 = "Joyjeet is my name"
s2 = "I am an Indian"

In [114]:
print(np.char.add(s1, s2))

Joyjeet is my nameI am an Indian


In [115]:
np.char.upper(s1)

array('JOYJEET IS MY NAME', dtype='<U18')

In [116]:
np.char.lower(s1)

array('joyjeet is my name', dtype='<U18')

In [117]:
np.char.split(s1)

array(list(['Joyjeet', 'is', 'my', 'name']), dtype=object)

In [118]:
s3 = "Joyjeet is my \nname"
np.char.splitlines(s3)

array(list(['Joyjeet is my ', 'name']), dtype=object)

In [128]:
print(np.char.replace(s1, 'name', 'surname'))

Joyjeet is my surname


In [121]:
print('***********good bye**********')

***********good bye**********


In [127]:
print(np.char.center('good bye', 28, '*'))

**********good bye**********
