In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]);
print(arr)

[1 2 3 4 5]


In [3]:
data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print(data1, type(data1), arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'> [1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
print(list(range(1,5)))
data2 = [range(1,5), range(5,9)]
arr2 = np.array(data2)
print(data2, type(data2))
print(arr2, type(arr2))

[1, 2, 3, 4]
[range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [5]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]
